<#
.SYNOPSIS
  Regenerates ushur_monthly_data.js from all UshurHub CSV files in this folder.

.DESCRIPTION
  Reads every UshurHub_MONTHLY_*.csv file found in the data folder,
  organises them by month name, and writes two window globals:
    - window.USHUR_MAY_DATA  (from UshurHub_MONTHLY_May2026.csv)
    - window.USHUR_JUNE_DATA (from UshurHub_MONTHLY_June2026.csv)
  Add future months as UshurHub_MONTHLY_<Month><Year>.csv and
  update the $monthMap below.

.USAGE
  From this folder, run:
    .\generate_ushur_data.ps1

  Or with explicit paths:
    .\generate_ushur_data.ps1 -DataDir "path\to\data" -OutFile "ushur_monthly_data.js"
#>

param(
    [string]$DataDir = $PSScriptRoot,
    [string]$OutFile = (Join-Path $PSScriptRoot "ushur_monthly_data.js")
)

# Map filename keywords -> window variable name
$monthMap = [ordered]@{
    "May2026"  = "USHUR_MAY_DATA"
    "June2026" = "USHUR_JUNE_DATA"
    "July2026" = "USHUR_JULY_DATA"
    "Aug2026"  = "USHUR_AUG_DATA"
    "Sep2026"  = "USHUR_SEP_DATA"
    "Oct2026"  = "USHUR_OCT_DATA"
    "Nov2026"  = "USHUR_NOV_DATA"
    "Dec2026"  = "USHUR_DEC_DATA"
}

function EscapeJsonValue([string]$val) {
    return $val `
        -replace '\\', '\\' `
        -replace '"', '\"' `
        -replace "`r", '' `
        -replace "`n", ' '
}

function RowToJson([pscustomobject]$row) {
    $parts = @()
    foreach ($p in $row.PSObject.Properties) {
        $k = EscapeJsonValue $p.Name
        $v = EscapeJsonValue ([string]$p.Value)
        $parts += """$k"":""$v"""
    }
    return "{" + ($parts -join ",") + "}"
}

$csvFiles = Get-ChildItem -Path $DataDir -Filter "UshurHub_MONTHLY_*.csv" | Sort-Object Name

if ($csvFiles.Count -eq 0) {
    Write-Warning "No UshurHub_MONTHLY_*.csv files found in $DataDir"
    exit 1
}

$sb = [System.Text.StringBuilder]::new()
$genDate = Get-Date -Format 'yyyy-MM-dd HH:mm'
[void]$sb.AppendLine("// Auto-generated by generate_ushur_data.ps1 - do not edit manually")
[void]$sb.AppendLine("// Generated: $genDate")
[void]$sb.AppendLine("//")

foreach ($csv in $csvFiles) {
    # Identify which window variable to use
    $varName = $null
    foreach ($key in $monthMap.Keys) {
        if ($csv.Name -like "*$key*") {
            $varName = $monthMap[$key]
            break
        }
    }

    if (-not $varName) {
        # Fallback: derive variable name from filename
        # UshurHub_MONTHLY_October2026.csv -> USHUR_OCTOBER2026_DATA
        $suffix = ($csv.BaseName -replace 'UshurHub_MONTHLY_', '').ToUpper()
        $varName = "USHUR_${suffix}_DATA"
    }

    Write-Host "Processing $($csv.Name) -> window.$varName"
    $rows = Import-Csv $csv.FullName

    $cnt = $rows.Count
    [void]$sb.AppendLine("// Source: $($csv.Name) - $cnt rows")
    $winVar = "window.$varName"
    [void]$sb.Append("$winVar = [")
    $jsonRows = $rows | ForEach-Object { RowToJson $_ }
    [void]$sb.AppendLine(($jsonRows -join ",`n"))
    [void]$sb.AppendLine("];")
    [void]$sb.AppendLine("")
}

[System.IO.File]::WriteAllText($OutFile, $sb.ToString(), [System.Text.Encoding]::UTF8)
$sz = [Math]::Round((Get-Item $OutFile).Length / 1KB, 0)
Write-Host "Written: $OutFile - $sz KB" -ForegroundColor Green
Write-Host "The Monthly Engagement.html will pick up the new data on next open." -ForegroundColor Cyan
